### ISSUE TITLE
Login & register

### ISSUE THREAD

**Issue by Leofuchs200811** [neatnik/terminal.land#125]
Hello, I have a question
All commands on the site require the user to be registered or logged into the account, however, the site shows that it is not possible to create an account or log in to it, is this already being done?

**Comment by newbold** [comment]
Hello! And apologies for not offering a better explanation for the issue on the site itself. I've since added a short thread about it on Twitter: https://twitter.com/TerminalLand/status/1350204735626866694

Once I've worked out a process for pre-screening folks, I'll post about that in the [Discussions](https://github.com/neatnik/terminal.land/discussions) section of this repo (which I've just enabled).
