### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by Leofuchs200811** [neatnik/terminal.land#126]
Hello, I have a question regarding the connection of the site, is there any other site besides [Terminal Land 1](https://terminal.land/) and [Terminal Land 2](http://terminal.site/)? And what does it mean to be disconnected?, because, as I said in Issue #125, all the typed commands show "``You’ll need to LOGIN or REGISTER before you can do that.``"

**Comment by newbold** [comment]
The first link is the canonical site URL (i.e. the one you should use), and the second was a temporary placeholder that is no longer active. In the upper-right corner your connection status is displayed. There are three possible states: "Disconnected", which means the client does not have an active connection to the server; "Connected", which means an active connection exists (which is made upon successful login), and "Reconnecting", which happens when the connection is interrupted. So, until login/registration is back online, "Disconnected" is the expected state. Sorry for the confusion!

**Comment by Leofuchs200811** [comment]
No problem, thanks for the help!
