### ISSUE TITLE
Text disappears when typing too quickly (after sending another command)

### ISSUE THREAD

**Issue by leabmgrt** [neatnik/terminal.land#67]
This is a minor bug but when you type `"hi` and then quickly start typing something else after sending the textfields gets cleared (`"hi` -> *send* -> textfield cleared -> type something -> "lea says "hi"" appears -> **textfield cleared**)

**Comment by newbold** [comment]
Thanks for catching this! It turns out that I was clearing the input value twice after pressing enter -- once almost right away, and then a second time after the `fetch()` completed. I think that second time (which had no business being there) was interfering. Let me know if you still see this behavior, though!
